version: "3"
services:
  db:
    image: postgres:15
    container_name: time_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: .
    container_name: time_backend
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
